# Generated by Django 4.1.3 on 2022-11-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_personales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjería')], max_length=50, verbose_name='Tipo de documento')),
                ('documento', models.IntegerField(verbose_name='Numero de documento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completos')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('IT', 'Intersexual'), ('I', 'Indefinido'), ('N', 'Prefiero no decir')], max_length=50, verbose_name='Genero')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio de residencia')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('localidad', models.CharField(max_length=50, verbose_name='Barrio - Localidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('etnia', models.CharField(choices=[('NINGUNA', 'Ninguno'), ('AFRO', 'Afro'), ('INDIGENA', 'Indigena'), ('RAIZAL', 'Raizal'), ('PALENQUERO', 'Palenquero'), ('GITANO', 'Gitano')], max_length=50, verbose_name='Etnia')),
                ('discapacidad', models.CharField(choices=[('AUDITIVO', 'Auditivo'), ('VISUAL', 'Visual'), ('MOVILIDAD', 'Movilidad'), ('NINGUNO', 'Ninguno')], max_length=50, verbose_name='Condición de discapcidad')),
                ('estrato', models.CharField(max_length=50, verbose_name='Estrato socieconómico')),
                ('educacion', models.CharField(choices=[('PRIMARIA', 'Básica Primaria'), ('SECUNDARIA', 'Básica secundaria'), ('BACHILLER', 'Bachiller académico'), ('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('PROFESIONAL', 'Profesional')], max_length=50, verbose_name='Nivel educativo alcanzado')),
                ('acceso', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=10, verbose_name='Acceso a dispositivos tecnológicos')),
                ('dispositivos', models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('COMPUTADOR', 'Computador'), ('SMARTPHONE', 'Smartphone'), ('OTRO', 'Otro')], max_length=50, null=True, verbose_name='Dispositivos con acceso')),
                ('conectividad', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=10, verbose_name='Conectividad a internet')),
                ('regimen', models.CharField(choices=[('CONTRIBUTIVO', 'Contributivo'), ('SUBSIDIADO', 'Subsidiado')], max_length=20, verbose_name='Regimen de afiliación')),
            ],
        ),
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('passwordConfirm', models.CharField(max_length=50, verbose_name='Confirmar contraseña')),
            ],
        ),
    ]
